plugins {
    id 'net.neoforged.moddev' version '2.0.141' apply false
}

subprojects {
    apply plugin: 'java'

    group = mod_group
    version = mod_version

    java.sourceCompatibility = java.targetCompatibility = JavaVersion.toVersion(java_version)

    repositories {
        // Spongepowered
        maven { url = 'https://repo.spongepowered.org/maven/' }
    }

    tasks.withType(Jar).configureEach {
        manifest {
            attributes([
                'Specification-Title': mod_id,
                'Specification-Vendor': mod_author,
                'Specification-Version': '1',
                'Implementation-Title': mod_name,
                'Implementation-Version': mod_version,
                'Implementation-Vendor': mod_author,
                'Implementation-Timestamp': new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
            ])
        }

        metaInf {
            from rootProject.file('LICENSE.txt')
        }
    }
}
