# Gradle
org.gradle.jvmargs=-Xmx2G
org.gradle.configuration-cache=false

# Mod
mod_id=jesustotem
mod_name=Jesus' Totem
mod_version=0.1.0
mod_group=com.cooldie.jesustotem
mod_license=MIT
mod_author=Camper CoolDie
mod_description=This mod adds godly screen & sound effects to the Totem of Undying. Experience the power of God!

# Lowest Minecraft version supported by this mod
minecraft_version=1.21.5
# Range of Minecraft versions supported by this mod
minecraft_version_range=1.21.5
# Lowest Java version supported by `minecraft_version`
java_version=21
# Latest Parchment version supported by `minecraft_version`
parchment_version=2025.04.19

# Fabric + Quilt

# Lowest Fabric Loader version supported by `minecraft_version`
fabric_loader_version=0.16.10
# Lowest Mod Menu version supported by `minecraft_version`
fabric_mod_menu_version=14.0.0-rc.1

# NeoForge

# Lowest NeoForge version supported by `minecraft_version`
neoforge_version=21.5.74
