# Gradle
org.gradle.jvmargs=-Xmx2G
org.gradle.configuration-cache=false

# Mod
mod_id=jesustotem
mod_name=Jesus' Totem
mod_version=0.2.1
mod_group=com.cooldie.jesustotem
mod_license=MIT
mod_author=Camper CoolDie
mod_description=This mod adds godly screen & sound effects to the Totem of Undying. Experience the power of God!

minecraft_version=26.1.2
minecraft_version_range=26.1
java_version=25

# Fabric + Quilt
fabric_loom_version=1.17.14
fabric_loader_version=0.19.3
fabric_mod_menu_version=18.0.0

# NeoForge
neoforge_moddev_version=2.0.141
neoforge_minecraft_version=26.1.2
neoforge_version=26.1.2.78
neoforge_version_range=26.1.2
