apply plugin: 'net.neoforged.moddev'

base.archivesName = "$mod_id-neoforge-mc$neoforge_minecraft_version"
neoForge.version = neoforge_version

dependencies {
    // Mixin
    compileOnly 'org.spongepowered:mixin:0.8.7'
}

tasks.withType(ProcessResources).configureEach {
    filesMatching(['META-INF/neoforge.mods.toml']) {
        expand([
            'mod_id':                  mod_id,
            'mod_name':                mod_name,
            'mod_version':             mod_version,
            'mod_license':             mod_license,
            'mod_author':              mod_author,
            'mod_description':         mod_description,
            'minecraft_version_range': minecraft_version_range,
            'neoforge_version_range':  neoforge_version_range,
        ])
    }
}
